In [1]:
import pandas as pd
import numpy as np
import itertools
import lightgbm as lgbm
import matplotlib.pyplot as plt

from script import *
from feature_engineering import *
import db_operations as dbop
from constants import *
import data_process as dp

import time

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
pd.set_option('display.max_rows',200)
idx = pd.IndexSlice
agg_operations =['mean','median','max','min','std','size']

In [3]:
start = 20100101
cursor = dbop.connect_db("sqlite3").cursor()

df_d = dbop.create_df(cursor, STOCK_DAY[TABLE], start=start)
df_d = dp.proc_stock_d(dp.prepare_stock_d(df_d))
df_d.drop(columns=['open0','high0','low0','vol0'],inplace=True)
df_d['pct'] = df_d.sort_index().groupby('code')['close'].pct_change()*100
df_d['amt']/=1e5
df_d = df_d.astype('float32')
print(df_d.columns)
print(df_d.shape)
df_d.info(memory_usage='deep')
df_d.tail()

select * from stock_day where date>=20100101
Index(['open', 'high', 'low', 'close', 'vol', 'amt', 'adj_factor', 'avg',
       'close0', 'avg0', 'pct'],
      dtype='object')
(3073431, 11)
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3073431 entries, (000001.SZ, 2010-01-04 00:00:00) to (603997.SH, 2020-04-17 00:00:00)
Data columns (total 11 columns):
open          float32
high          float32
low           float32
close         float32
vol           float32
amt           float32
adj_factor    float32
avg           float32
close0        float32
avg0          float32
pct           float32
dtypes: float32(11)
memory usage: 220.8 MB

                           open       high        low      close  \
code      date
603997.SH 2020-04-13  14.538041  14.945041  14.033360  14.782240
          2020-04-14  14.733400  15.466001  14.521760  15.107840
          2020-04-15  15.107840  15.205521  14.326401  14.391521
          2020-04-16  14.293839  14.652000  14.098480  14.505480
          2020-04-17  14.293839  14.961320  14.179880  14.456640

                                vol       amt  adj_factor        avg  close0  \
code      date
603997.SH 2020-04-13  248891.234375  3.608364       1.628  14.497756    9.08
          2020-04-14  272612.593750  4.106719       1.628  15.064303    9.28
          2020-04-15  219103.843750  3.220524       1.628  14.698620    8.84
          2020-04-16  164169.046875  2.359027       1.628  14.369497    8.91
          2020-04-17  196805.343750  2.856015       1.628  14.511876    8.88

                          avg0       pct
code      date
603997.SH 2020-04-13  8.905255  0.776911
          2020-04-14  9.253258  2.202642
          2020-04-15  9.028636 -4.741371
          2020-04-16  8.826472  0.791848
          2020-04-17  8.913929 -0.336695

In [4]:
df_d_basic = dbop.create_df(cursor, STOCK_DAILY_BASIC[TABLE], start=start)
df_d_basic = dp.prepare_stock_d_basic(df_d_basic)
#
df_d_basic["pb*pe_ttm"] = df_d_basic["pb"] * df_d_basic["pe_ttm"]
df_d_basic["pb*pe"] = df_d_basic["pb"] * df_d_basic["pe"]

df_d_basic = df_d_basic.astype('float32')
print(df_d_basic.columns)
print(df_d_basic.shape)
df_d_basic.info(memory_usage='deep')
df_d_basic.index.tail()

select * from stock_daily_basic where date>=20100101
Index(['close', 'turnover_rate', 'turnover_rate_f', 'volume_ratio', 'pe',
       'pe_ttm', 'pb', 'ps', 'ps_ttm', 'total_share', 'float_share',
       'free_share', 'total_mv', 'circ_mv', 'pb*pe_ttm', 'pb*pe'],
      dtype='object')
(2913386, 16)
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2913386 entries, (000001.SZ, 2010-01-04 00:00:00) to (603997.SH, 2020-04-17 00:00:00)
Data columns (total 16 columns):
close              float32
turnover_rate      float32
turnover_rate_f    float32
volume_ratio       float32
pe                 float32
pe_ttm             float32
pb                 float32
ps                 float32
ps_ttm             float32
total_share        float32
float_share        float32
free_share         float32
total_mv           float32
circ_mv            float32
pb*pe_ttm          float32
pb*pe              float32
dtypes: float32(16)
memory usage: 189.0 MB

AttributeError: 'MultiIndex' object has no attribute 'tail'

In [ ]:
df = df_d
periods = [5,10,20,30,60,120,250]
for k in periods:
    df['{:d}ma'.format(k)]=df.reset_index('code').groupby('code')['close'].rolling(k).mean()
print(df.columns)
    
for col2 in ["{}ma".format(k) for k in periods]:
    col1 = 'close'
    df['{}/{}'.format(col1,col2)] = df[col1]/df[col2]
print(df.columns)